version: "3.9"

services:
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: ./entrypoint.sh
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
